PyCommunity/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^forum/', include('forum.urls', namespace="forum")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('registration.urls')),
)

forum/urls.py
#imports(
from django.conf.urls import *
from django.contrib.auth.decorators import login_required as LR
from models import *
from views import *
#)
#==========================================================================================
urlpatterns = patterns('',
    url(r"^forum/(?P<dpk>\d+)/$", ForumView.as_view(), name= "forum"),
    url(r"^topic/(?P<dpk>\d+)/$", TopicView.as_view(), name= "topic"),
    url(r"^new_topic/(?P<dpk>\d+)/$"  , LR(NewTopic.as_view()), name= "new_topic"),
    url(r"^reply/(?P<dpk>\d+)/$" , LR(Reply.as_view()), name="reply"),
    url(r"^profile/(?P<pk>\d+)/$"  , LR(EditProfile.as_view()), name="profile"),
    url(r"^viewprofile/(?P<dpk>\d+)/$" , LR(UserPageView.as_view()), name="viewprofile"),
    url(r"^new_wallpost/(?P<dpk>\d+)/$"  , LR(NewWallpost.as_view()), name= "new_wallpost"),
    url(r"^(?P<pk>\d+)/like/$", LR(like), name='like'),
    url(r"^(?P<pk>\d+)/friendlist/$", LR(friendsList), name="friendlist"),
    url(r"^(?P<pk>\d+)/addfriend/$", LR(friendAdd),name="addfriend"),
    url(r"^(?P<pk>\d+)/removefriend/$", LR(friendRemove),name="removefriend"),
    url(r"^$", Main.as_view(), name="main"),
)

forum/models.py
#imports(
from django.core.mail import send_mail
from django.db.models import *
from django.contrib.auth.models import User
from django.contrib import admin
from django.db.models.signals import post_save
from  utils import *
#)
#==========================================================================================
class UserProfile(BaseModel):
    avatar = URLField(max_length=200)
    posts  = IntegerField(default=0)
    user   = OneToOneField(User, related_name="profile")
    name=CharField(max_length=60)
    country=CharField(max_length=60)
    scores=IntegerField(default=0)
    status=TextField(max_length=500)
    personalDetails= TextField(max_length=1000)
    

    def __unicode__(self):
        return unicode(self.user)

    def get_absolute_url(self) :
        """it gets the absolute url of current user page , this method has been used in views"""
        return reverse("forum:viewprofile",args=[self.pk])

    def incrementPosts(self):
        """this method will be used for each new post to increment the number of user's posts"""
        self.posts += 1
        self.save()
        
    def incrementScores(self):
        """this method will be used for each new post to increment the number of user's post"""
        self.scores += 1
        self.save()
        
#==========================================================================================

class Forum(BaseModel):
    
    title = CharField(max_length=60)
    
    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
       """ it gets the absolute url of current forum page , this method has been used in views"""
       return reverse("forum:forum",args=[self.pk])

    def numPosts(self):
        """returns the total number of  the posts in each forum"""
        return sum([t.numPosts() for t in self.topics.all()])

    def lastPost(self):
        """finds the last post of all the topics in a forum"""
        topics = self.topics.all()# the list of topics in a forum
        last    = None
        for topic in topics:#like finding the maximum of a list
            templastp = topic.lastPost()
            if templastp and (not last or templastp.date > last.date):
                last = templastp
        return last

#==========================================================================================
class Topic(BaseModel):
    title   = CharField(max_length=60)
    date = DateTimeField(auto_now_add=True)
    creator = ForeignKey(User, blank=True, null=True)
    forum   = ForeignKey(Forum, related_name="topics")

    class Meta:
        ordering = ["-date"]# order topics by their date of creation

    def __unicode__(self):
        return unicode("%s - %s" % (self.creator, self.title))

    def get_absolute_url(self) :
        """ it gets the absolute url of current topic page, this method has been used in views"""
        return reverse("forum:topic", args=[self.pk])
    
    def lastPost(self)  :
        """returns the most recent post of the topic"""
        return first(self.posts.all())#the first post is the recent post
    
    def numPosts(self) :
        """returns the number of  the posts in each topic"""
        return self.posts.count()
    
    def numReplies(self) :
        """returns the number of the replies in each topic"""
        return self.posts.count() - 1#because the first post isn't a reply
    
#==========================================================================================
class Post(BaseModel):
    title = CharField(max_length=60)
    date = DateTimeField(auto_now_add=True)
    creator=ForeignKey(User, blank=True, null=True)
    topic = ForeignKey(Topic, related_name="posts")
    body = TextField(max_length=10000)

    class Meta:
        ordering = ["date"]

    def __unicode__(self):
        return u"%s - %s - %s" % (self.creator, self.topic, self.title)

    def short(self):
        """this method is used in lastposts column to show creator and title and date"""
        date = self.date.strftime("%b %d, %I:%M %p")
        return u"%s - %s\n%s" % (self.creator, self.title, date)

    def profileData(self):
        """this method is used in each post to see the creator's avatar and number of his posts"""
        p = self.creator.profile
        return p.posts, p.avatar
#===========================================================================================
class Wallpost(BaseModel):
    creator = ForeignKey(User, blank=True, null=True)
    body = TextField(max_length=1000)
    profile = ForeignKey(UserProfile, related_name="wallposts",  blank=True, null=True)
    date = DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ["date"]    
    def __unicode__(self):
        return u"%s: %s" % (self.profile, self.body[:60])

    def save(self, *args, **kwargs):
        if self.creator!=self.profile.user:
            """email when a wallpost is added."""
            message        = "Wallpost  was added to your profile page  by '%s':\n%s" % ( self.creator, self.body)
            from_addr      = "pycommunity.noreply@gmail.com"
            recipient_list = [self.profile.user.email]
            send_mail("New Wallpost Added", message, from_addr, recipient_list)
        super(Wallpost, self).save(*args, **kwargs)
#==========================================================================================
class Friendship(Model):
    fromFriend = ForeignKey(User, related_name='friendSet')
    toFriend = ForeignKey(User, related_name='toFriendSet')
    
    def submitted(self):
        """"the friendship is submitted if it has tow sides."""
        if Friendship.objects.filter(fromFriend=self.toFriend,toFriend=self.fromFriend):
            return True
        return False
    def __unicode__(self):
        return u'%s, %s' % (self.fromFriend.username,self.toFriend.username)
    
    class Meta:
        """the friendship sides must be unique"""
        unique_together = (('toFriend', 'fromFriend'), )
        

forum/forms.py
#imports(
from django.forms import ModelForm
from models import *
from utils import ContainerFormMixin
#)
#====================================================================================
class PostForm(ContainerFormMixin, ModelForm):
    """post form class which contains all the fields except creator and topic fields."""
    class Meta:
        model   = Post
        exclude = ["creator", "topic"]
#=====================================================================================        
class WallpostForm(ModelForm):
    """wallpost form which contains all the fields except creator and profile page fields."""
    class Meta:
        model = Wallpost
        exclude = ["profile","creator"]

forum/views.py
# imports (
from models import *
from utils import *
from django.views.generic.edit import  UpdateView as gUpdateView
from django.shortcuts import get_object_or_404
from mcbv.detail import DetailView
from mcbv.edit import CreateView, UpdateView
from mcbv.list_custom import ListView, ListRelated,DetailListCreateView
from forms import PostForm , WallpostForm
# )
#=========================================================================================
class Main(ListView):
    """desplays list of forums names and their last post."""
    list_model    = Forum
    template_name = "list.html"
#=========================================================================================
class ForumView(ListRelated):#(listview+detailview)
    """desplays all of the topics in each forum"""
    detail_model  = Forum
    list_model    = Topic
    related_name  = "topics"
    template_name = "forum.html"
#=========================================================================================
class TopicView(ListRelated):
    """desplays all of the posts in each topic"""
    list_model    = Post
    detail_model  = Topic
    related_name  = "posts"
    template_name = "topic.html"
#=========================================================================================
class UserPageView(ListRelated):
    """ desplays the fields of user's profile and all of the wallposts"""
    list_model    = Wallpost
    detail_model  = UserProfile
    related_name  = "wallposts"
    template_name = "userpage.html"
#=========================================================================================
class EditProfile(gUpdateView):
    """to update the profile fields by this view """
    model = UserProfile
    fields = ['name','country','avatar','status', 'personalDetails']
    template_name_suffix = '_update_form'
#=========================================================================================
class NewWallpost(DetailView, CreateView):
    
    detail_model = UserProfile
    form_model = Wallpost
    modelform_class = WallpostForm
    body = "New Wallpost"
    template_name = "wallpost.html"

    def get_profile(self, modelform):
        """ gives the current profile object"""
        return self.get_detail_object()

    def modelform_valid(self, modelform):
        """ creates a new wallpost on a profile page """
        body = modelform.cleaned_data['body']
        profile = self.get_profile(modelform)
        Wallpost.obj.create(profile=profile,body=body, creator=self.user)
        return redir(self.get_success_url())

    def get_success_url(self):
        return self.get_detail_object().get_absolute_url()
#=========================================================================================
class NewTopic(DetailView, CreateView):
    detail_model = Forum
    form_model = Post
    modelform_class = PostForm
    title = "Start New Topic"
    template_name = "post.html"

    def get_topic(self, modelform):
        """ creates a topic in the current forum"""
        title = modelform.cleaned_data.title
        return Topic.obj.create(forum=self.get_detail_object(), title=title, creator=self.user)

    def modelform_valid(self, modelform):
        """creates first post of the new topic """
        data   = modelform.cleaned_data
        topic = self.get_topic(modelform)
        Post.obj.create(topic=topic, title=data.title, body=data.body, creator=self.user)
        self.user.profile.incrementPosts()
        return redir(self.get_success_url())

    def get_success_url(self):
        return self.get_detail_object().get_absolute_url()

#=========================================================================================
class Reply(NewTopic):

    detail_model = Topic
    title = "Reply"
    
    def get_topic(self, modelform):
        """gives the current topic class to save a reply in it"""
        return self.get_detail_object()

    def get_success_url(self):
        """brings back the user to current topic page"""
        return self.get_detail_object().get_absolute_url() + "?page=last"
#=========================================================================================
def like(request, pk):
    """ when a user press the like buttons the number of post creator's score will be increased
        and an email will be sent to postcreator"""
    post = get_object_or_404(Post, pk=pk)
    topic=post.topic
    user=request.user
    
    post.creator.profile.incrementScores()
    
    message=  "%s (%s) Liked  your post :%s(%s)"% (user,'http://localhost:8000/forum/viewprofile/%d/'%(user.id), post,'http://localhost:8000/forum/topic/%d/'%(topic.id))
                                
    recipient_list = [post.creator.email]
    from_addr="pycommunity.noreply@gmail.com"
    send_mail("Like Notification", message, from_addr, recipient_list)
    
    return HttpResponseRedirect(reverse('forum:topic', args=(topic.id,)))
#==========================================================================================
def friendsList(request, pk):
    """ shows the list of user's page . """
    user = get_object_or_404(User, pk=pk)
    friends = [friendship.toFriend for friendship in user.friendSet.all() if friendship.submitted()]
    
    variables = RequestContext(request,{ 'friends': friends})
    return render_to_response('friendsListPage.html', variables)
#==========================================================================================
def friendAdd(request,pk):
    """this function  saves a side of a friendship and email to friend,if friend adds the user too,
        their friendship will be submitted
        and bring back the user to the friend's profile page"""
    user=request.user
    friend = get_object_or_404(User,pk=pk)
    
    friendship = Friendship(fromFriend=user,toFriend=friend)
    friendship.save()
    
    if friendship.submitted():
        message        =  "friendship with %s(%s) has been submitted."% (user,'http://localhost:8000/forum/viewprofile/%d/'%(user.id))
    else:
        message =  "%s (%s) added you to her(him) friend list,if you want to submit this friendship add her(him) to your friends list. "% (user,'http://localhost:8000/forum/viewprofile/%d/'%(user.id))
                                
    from_addr  ="pycommunity.noreply@gmail.com"
    recipient_list = [friend.email]
    send_mail("Friendship Notification", message, from_addr, recipient_list)
    
    return HttpResponseRedirect(reverse('forum:viewprofile' ,args=(friend.pk,)))
#==========================================================================================
def friendRemove(request,pk):
    """this function  removes the both sides of friendship
        and bring back the user to the friend's profile page"""
    user=request.user
    friend = get_object_or_404(User,pk=pk)
    
    friendship1 = Friendship.objects.get(fromFriend=request.user, toFriend=friend)
    friendship1.delete()
    
    friendship2 = Friendship.objects.get(fromFriend=friend, toFriend=request.user)
    friendship2.delete()
    
    return HttpResponseRedirect(reverse('forum:viewprofile' ,args=(friend.pk,)))

forum/templates/fbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}ForumApp{% endblock %}</title>

    <style type="text/css">
        * {
            font-family:"Comic Sans MS", cursive, sans-serif;
            color: #555;
            font-size: 0.98em;
            word-wrap:break-word;
        }

        #menu a {
            font-family:"Comic Sans MS", cursive, sans-serif;
            text-decoration: none;
            background: #a6a6a6;
            border-top: 1px solid #ccc;
            border-bottom: 1px solid #ccc;
            border-right: 2px solid #fff;
            padding-right: 3px;
            padding-left: 3px;
            color: white;
            font-size: 1em;
        }

        a:hover {
            font-family:"Comic Sans MS", cursive, sans-serif;
            background: #eeebeb;
            border-top: 1px solid #aaa;
            border-bottom: 1px solid #aaa;
            color: #555;
        }
        body 
        {
        background-image:url('http://s29.postimg.org/ckbodf7tj/bg2.jpg');
        }
        #container { margin: auto; width: 700px; border: 0px solid; }

        p { font-family:"Comic Sans MS", cursive, sans-serif;font-size: 1.1em;background:white; }
        h3 { margin-right: 30px; display: inline; }
    </style>

</head>

<body>
    <div id="sidebar"> {% block sidebar %} {% endblock %} </div>
    <div id="container">
        <div id="menu">
            {% block nav-global %}

                <!-- MENU -->
            {% load staticfiles %}
            <form method="get" action="http://www.google.com/search">
            <input type="text"   name="q" size="31" maxlength="255" value="" />
            <input type="submit" value="Google Search" /><br /><br />
            </form>
                <h3><a href="{% url 'forum:main' %}">Forums</a></h3>

                {% if user.is_staff %} <a href="{% url 'admin:index' %}">Admin</a> {% endif %}
                {% if user.is_authenticated %}
                    <a href="{% url 'forum:profile' user.pk %}">Edit profile</a> 
                    <a href="{% url 'forum:viewprofile' user.pk %}">My Page</a>
                    <a href="{% url 'forum:friendlist' user.pk %}">My Friends List</a> {% endif %}

                {% if not user.is_authenticated %}<a href="/accounts/login/?next=/forum/">login</a> | <a
                    href="/accounts/register/">register</a>{% endif %}

                {% if user.is_authenticated %}<a href="/accounts/logout/?next=/forum/">logout</a>
                    {% endif %}

            {% endblock %}
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

forum/templates/forum.html
{% extends "fbase.html" %}

{% block sidebar %} <style type="text/css"> </style> {% endblock %}

{% block content %}
    <style type="text/css">
        .pagination { margin-top: 20px; margin-left: -20px; }
        .main { margin-left: 25px; margin-top: 30px; width: 700px; }
        .title { font-size: 1.4em; margin-top: 0px; padding-left: 4px; }
        .last { border: 0px; }
        .title a { text-decoration: none; }
        .button { background: #999; color: white; padding: 4px; text-decoration: none; }
        .buttont { background: #999; color: white; padding: 2px; text-decoration: none; }

        td { border-bottom: 1px solid #ccc; }
        #list { border: 1px solid #ccc; width: 700px;background:white; }
        #new_topic { float: right; }
    </style>

    <div class="main">

      <a id="new_topic" class="buttont" href=
        "{% url 'forum:new_topic' forum.pk %}">Start New Topic</a>
        <br />
        <br />

      <div id="list">
          {% if topic_list %}
            <table border="0" cellpadding="4" width="100%">
                <tr>
                    <td>Topics</td>
                    <td>Replies</td>
                    <td>Last post</td>
                    <td></td>
                </tr>

                <!-- Topics  -->
                {% for topic in topic_list %}
                <tr {% if forloop.last %}class="last"{% endif %}>
                    <td>
                        <div class="title"> <a href="{% url 'forum:topic' topic.pk %}">{{ topic.title }}</a></div>
                    </td>
                    <td>{{ topic.numReplies }}</td>
                    <td>{{ topic.lastPost.short|linebreaksbr }}</td>
                    <td><a class="button" href="{% url 'forum:topic' topic.pk %}">VIEW</a></td>
                </tr>

                {% endfor %}
            </table>
        {% else %}
          <blockquote>No topics in this forum yet..</blockquote>
        {% endif %}
        </div>
        {% include "pagination.html" %}
        </div>
{% endblock %}

forum/templates/friendsListPage.html
{% extends "fbase.html" %}

{% block sidebar %} <style type="text/css"> </style> {% endblock %}

{% block content %}
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px; }
         #list { border: 1px solid #a6cccc; width: 500px; background: #f6f6f6; }
    </style>

    <div class="main">
    <h2>Friend List</h2>
        <div class="list">
            {% if friends %}
                {% for friend in friends %}
                    <img src="{{ friend.profile.avatar }}" alt="No Profile picture" height="100" width="100"/> <br />
                    <li><a href="{% url 'forum:viewprofile' friend.pk %}">{{ friend }}</a></li>
                {% endfor %}
         </div>
    {% else %}
        
        <center><p>No friends found.</p></center>
    {% endif %}
    </div>
{% endblock %}

forum/templates/list.html
{% extends "fbase.html" %}

{% block sidebar %} <style type="text/css"> </style> {% endblock %}

{% block content %}
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px;background:white;}
        .title { font-size: 1.4em; margin-top: 10px; border-bottom: 0px solid #ccc; padding-left: 4px;background:white; }
        .last { border: 0px; }
        .title a { text-decoration: none; }
        .button { background: #999; color: white; padding: 4px; text-decoration: none; }

        td { border-bottom: 1px solid #ccc; }
        #list { border: 1px solid #ccc; width: 700px;background:white; }
    </style>

    <div class="main">

        <div id="list">
        <table border="0" cellpadding="4" width="100%">
            <tr>
                <td></td>
                <td>Posts</td>
                <td>Last post</td>
                <td></td>
            </tr>

            <!-- Forums  -->
            {% for forum in forum_list %}
            <tr{% if forloop.last %}class="last"{% endif %}>
                <td>
                    <div class="title"> <a href="{% url 'forum:forum' dpk=forum.pk %}">{{ forum.title }}</a></div>

                </td>
                <td>{{ forum.numPosts }}</td>
                <td>{{ forum.lastPost.short|linebreaksbr }}</td>
                <td><a class="button" href="{% url 'forum:forum' dpk=forum.pk %}">VIEW</a></td>
            </tr>

            {% endfor %}
        </div>

    </div>

{% endblock %}

forum/templates/pagination.html
{% load admin_list %}
{% load i18n %}
<p class="paginator">
{% if pagination_required %}
{% for i in page_range %}
    {% paginator_number cl i %}
{% endfor %}
{% endif %}
{{ cl.result_count }} {% ifequal cl.result_count 1 %}{{ cl.opts.verbose_name }}{% else %}{{ cl.opts.verbose_name_plural }}{% endifequal %}
{% if show_all_url %}&nbsp;&nbsp;<a href="{{ show_all_url }}" class="showall">{% trans 'Show all' %}</a>{% endif %}
{% if cl.formset and cl.result_count %}<input type="submit" name="_save" class="default" value="{% trans 'Save' %}"/>{% endif %}
</p>

forum/templates/topic.html
{% extends "fbase.html" %}

{% block sidebar %} <style type="text/css"> </style> {% endblock %}

{% block content %}
    <style type="text/css">
        .pagination { margin-top: 20px; margin-left: -20px; }
        .main { margin-left: 25px; margin-top: 30px; width: 700px; }
        .title { font-size: 1.4em; margin-top: 10px; padding-left: 0px; }
        .title a { text-decoration: none; }
        .button { background: #999; color: white; padding: 6px; text-decoration: none; float: right; }
        .date { font-size: 0.8em; padding-left: 5px; }
        .ppic { float: right;margin: 8px; padding: 8px; margin-bottom: 14px; background: white; }
        .clear { clear: both; }
        #reply { margin-top: 10px; width: 500px; }

        .post {
            margin: 8px; padding: 8px; border: 1px solid #ccc; margin-bottom: 14px; background: white;
            }
        .ttitle {
            font-style: bold; font-size: 1.6em; border-bottom: 1px solid #ccc; margin-bottom: 9px;
            padding-left: 10px; width: 700px;
        }

        #list { border: 1.2px solid #a6cccc; width: 700px; background: #a6a6a6; }
        #back { margin: 5px; }
    </style>

    <div class="main">
<!-- Title and backlink -->
        <div class="ttitle">{{ topic.title }}</div>
        <div id="back">
            <a href="{% url 'forum:forum' topic.forum.pk %}">&lt;&lt; back to list of topics</a>
        </div>
        <div id="list">

            <!-- Posts  -->
            {% for post in post_list %}
                <div class="post">
                    <!-- Profile pic and info -->
                    <div class="ppic">
                        {% with post.profileData as pdata %}
                        <img src="{{ pdata.1 }}" alt="No Profile picture" height="100" width="100"/> <br />
                        {% if user.is_authenticated %}
                            crator: <a href="{% url 'forum:viewprofile' post.creator.pk %}">{{ post.creator }} <br /> </a> 
                            {%ifnotequal post.creator.pk user.pk %}
                                <a href="{% url 'forum:like' post.pk %}" target="_self" ><img src="http://s21.postimg.org/de438y3qf/thumbnail.jpg" height="25" width="25" border="0"/></a><br />{% endifnotequal %}{% endif %}
                        scores:{{ post.creator.profile.scores}}<br />
                        Posts: {{ pdata.0 }}<br />
                        {% endwith %}
                    </div>
                    <!-- Title, author and body -->
                    <span class="title">{{ post.title }}</span><br />
                    by {{ post.creator }} | <span class="date">{{ post.date }}</span> <br /><br />
                    {{ post.body|linebreaksbr }} <br />
                    <div class="clear"></div>
                </div>
            {% endfor %}
        </div>
        <!-- Paginator and reply link -->
        {% include "pagination.html" %}
        <br />
        <a class="button" href="{% url 'forum:reply' topic.pk %}">Reply</a>
    </div>


{% endblock %}

forum/templates/userpage.html
{% extends "fbase.html" %}

{% block sidebar %} <style type="text/css"> </style> {% endblock %}

{% block content %}
    <style type="text/css">
        .clear { clear: both; }
        .button { background: #a6a6a6; color: white; padding: 4px; text-decoration: none; float: right; }
        .date { font-size: 0.6em; padding-left: 5px; }
        .ppic { float: right;margin: 8px; padding: 8px; margin-bottom: 14px;margin-top: 14px; background: white; }
        #list { border: 1px solid #a6cccc; width: 500px; background: #a6a6a6; }
        .detail {
            margin: 2px;
            padding: 2px;
            border: 1px solid #ccc;
            margin-bottom: 10px;
            background: white;
            width:200px;
        }
        .title {
            margin: 2px;
            padding: 2px;
            background: #a6cccc;
            width:200px;

        }
           .wallpost {
            margin: 8px; padding: 8px; border: 1px solid #a6a6a6; margin-bottom: 14px; background: white;
            }
        .main { margin-left: 25px; margin-top: 30px; width: 300px; }
    </style>
<div class="main">
    <table width="100%"  border="0">
    <tr valign="top">
        <td style="background-color:#a6a6a6;
                    width:100px;text-align:top;">
        <center>
                    <div class="ppic"><img src="{{ userprofile.avatar }}"  alt="No Profile picture" height="200" width="200"/><br /></div>
            <br />
                    <div class="title">Name:</div>
                    <div class="detail"> {{ userprofile.name}}<br /></div>
                    <div class="title">Country:</div>
                    <div class="detail"> {{ userprofile.country}}<br /></div>
                    <div class="title">Email Address:</div>
                    <div class="detail">{{ userprofile.user.email }}<br /></div>
                    <div class="title">Posts:</div>
                    <div class="detail">{{ userprofile.posts }}<br /></div>
                    <div class="title">Scores:</div>
                    <div class="detail">{{ userprofile.scores }}<br /></div>
                    <div class="title">Status:</div>
                    <div class="detail">{{ userprofile.status |linebreaksbr }}<br /></div>
                    <div class="title">Last Login:</div>
                    <div class="detail">{{ userprofile.user.last_login|date:"M d Y" }}<br /></div>
                    <div class="title">Joined: </div>
                    <div class="detail">{{ userprofile.user.date_joined|date:"M d Y" }}<br /></div>
                    <div class="title">Personal Details:</div>
                    <div class="detail">{{ userprofile.personalDetails|linebreaksbr }}<br /></div>
                    {%ifnotequal userprofile.user.pk user.pk %}
                        {%if user.friendSet.all %}
                            {%for friendship in user.friendSet.all%}
                                {%ifequal userprofile.user.pk friendship.toFriend.pk%}
                                    {%if friendship.submitted%}
                                        <a href="{% url 'forum:friendlist' userprofile.user.pk %}"><div class="title">{{userprofile.user}}'s friends list</div></a>
                                        <a href="{% url 'forum:removefriend' userprofile.user.pk %}"><div class="title">Remove {{userprofile.user}} From Friend List </div></a>
                                    {%else%}
                                        <a href="{% url 'forum:addfriend' userprofile.user.pk %}"><div class="title">Add {{userprofile.user}} As A Friend </div></a>{%endif%}
                                {%endifequal%}
                            {%endfor%}
                        {%else%}
                            <a href="{% url 'forum:addfriend' userprofile.user.pk %}"><div class="title">Add {{userprofile.user}} As A Friend </div></a>{%endif%}
                    {% endifnotequal %}

                    </center>
        </td>
        <td style="background-color:#a6a6a6;height:100px;
                  width:200px;text-align:top;">
        {%for friendship in user.friendSet.all%}
            {%ifequal userprofile.user.pk friendship.toFriend.pk %}
            <a id="new_wallpost" class="button" href="{% url 'forum:new_wallpost' userprofile.pk %}">Add A New wallpost</a>
            {%endifequal%}
        {%endfor%}
        {%ifequal userprofile.user.pk user.pk %}
           <a id="A1" class="button" href="{% url 'forum:new_wallpost' userprofile.pk %}">Add A New Wallpost</a>
        {%endifequal%}
            <br />
        <div id="list">

            <!-- wallposts  -->
            {% for wallpost in wallpost_list %}
                <div class="wallpost">
                    <!-- Profile pic and info -->
                    <div class="ppic">
                        <center>
                        <img src="{{ wallpost.creator.profile.avatar }}" alt="No Profile picture" height="100" width="100"/> <br />
                        </center>
                        <a href="{% url 'forum:viewprofile' wallpost.creator.pk %}">{{ wallpost.creator }}<br /> </a>

                    </div>
                    <!--  author and body -->
                    by {{ wallpost.creator }} | <span class="date">{{ wallpost.date }}</span> <br /><br />
                    {{ wallpost.body|linebreaksbr }} <br />
                    <div class="clear"></div>
                </div>
            {% endfor %}
        </div>
        </td>
    </tr>
    <tr>
    </table>
</div>
{% endblock %}
    
    